"""
Run the entire sweetness-EEG pipeline (stages 01–10) and assemble REPORT_FULL.md.

Usage:
    .venv/bin/python sweetness_eeg/scripts/run_all.py
    .venv/bin/python sweetness_eeg/scripts/run_all.py --skip 09   # skip DL
"""

import _bootstrap  # noqa: F401
import argparse
import importlib
import os
import traceback

from swt.config import load_config, setup_logging, report_path

STAGES = [
    ('01', 'run_01_behavior', 'Behavioral (sensory) analysis'),
    ('02', 'run_02_preprocess_epoch', 'Preprocessing & epoching'),
    ('03', 'run_03_spectral_psd', 'Spectral / PSD (core)'),
    ('04', 'run_04_temporal_tfr', 'Temporal dynamics & TFR'),
    ('05', 'run_05_stats', 'Statistics'),
    ('06', 'run_06_erp', 'Onset-locked ERP'),
    ('07', 'run_07_connectivity', 'Frontal–gustatory connectivity'),
    ('08', 'run_08_ml', 'ML classification'),
    ('09', 'run_09_dl', 'DL classification'),
    ('10', 'run_10_eeg_behavior_corr', 'EEG ↔ behavior correlation'),
    ('11', 'run_11_channel_dose', 'Per-channel within-substance dose-response'),
    ('12', 'run_12_individual', 'Individual (per-subject) analysis & insights'),
]

REPORT_FILES = {
    '01': '01_behavior.md', '02': '02_preprocess.md', '03': '03_spectral_psd.md',
    '04': '04_temporal_tfr.md', '05': '05_stats.md', '06': '06_erp.md',
    '07': '07_connectivity.md', '08': '08_ml.md', '09': '09_dl.md',
    '10': '10_eeg_behavior_corr.md', '11': '11_channel_dose.md',
    '12': '12_individual.md',
}

INTRO = """# Neural Signatures of Sweetness Perception — Sucrose vs Sucralose (EEG)

*Self-contained analysis of the `data/datamoi/` recordings. Generated by the
`sweetness_eeg/` pipeline; legacy `pipeline/` and `src/` code is untouched.*

## Overview

Twenty-three participants tasted sucrose (S1) and sucralose (S2) at three iso-sweet
intensities (~5 / 7.5 / 12 % sucrose-equivalent) plus water, each presented twice for
10 s while 16-channel EEG (100 Hz) was recorded. This report reproduces the analyses
of the reference protocol — power spectral density of the five canonical bands
(δ, θ, α, β, γ) over **frontal** (reward/hedonic) and **gustatory** (insular/opercular
scalp-proxy) regions in both **time and frequency** domains, EEG **topographies**, the
contrast between **sucralose and sucrose**, the modulation of **frontal θ/α** by
sweetness intensity, and the **prolonged activation** linked to sucralose's lingering
aftertaste — and adds machine-/deep-learning classification, fronto-gustatory
connectivity, and EEG↔behaviour correlation.

## Sample mapping

| Label | Substance | Perceived intensity | Blind codes |
|:------|:----------|:--------------------|:------------|
| S1_5 / S1_7 / S1_12 | Sucrose | ~5 / 7.5 / 12 % | 119,452 / 781,299 / 873,777 |
| S2_5 / S2_7 / S2_12 | Sucralose | iso-sweet to 5 / 7.5 / 12 % | 563,453 / 336,122 / 257,644 |
| H2O | Water | baseline | 681, 575 |

## Methods (summary)

- **Loading**: robust to mixed CSV delimiters/decimals; channels T3/T4/T5/T6 renamed to
  T7/T8/P7/P8 (10-20 montage); µV → V.
- **Preprocessing**: average reference → 49 Hz notch → 0.5–45 Hz band-pass; 1000 µV
  peak-to-peak trial rejection.
- **Spectral**: Welch PSD (2 s, 50 % overlap); absolute & relative band power; ROI
  aggregation; Morlet TFR; sliding-window time-resolved power.
- **Statistics**: two-way rmANOVA (substance × intensity), FDR-corrected paired
  contrasts, cluster-based permutation on PSD.
- **Decoding**: LOSO cross-validation for ML (band-power features) and DL (raw epochs).

---
"""

DISCUSSION = """---

## Discussion (auto-generated scaffold)

The sections above map directly onto the reference paper's aims:

1. **PSD of five bands across frontal & gustatory regions** — Stage 03 (spectra,
   topographies, ROI band power) and Stage 05 (rmANOVA, cluster tests).
2. **Time + frequency domains** — Stage 03 (frequency) and Stage 04 (time-resolved
   power, TFR).
3. **EEG topographies differentiating sucralose from sucrose** — Stage 03
   sucrose−sucralose difference maps and Stage 05 contrasts/cluster tests.
4. **Frontal θ/α modulation by intensity (reward/hedonic)** — Stage 03 dose-response
   and Stage 10 correlation of frontal θ/α with liking/JAR.
5. **Prolonged activation / lingering aftertaste of sucralose** — Stage 01 residual
   aftertaste, Stage 04 late-vs-early window contrast.

**Additional analyses**: fronto-gustatory connectivity (Stage 07), ML/DL decoding of
substance and intensity (Stages 08–09), and the EEG↔behaviour bridge (Stage 10).

Quantitative conclusions should be read off the per-stage tables (effect sizes,
FDR-corrected p-values, decoding accuracy vs chance). Caveats: 23 subjects, a
consumer-grade 16-channel montage at 100 Hz (γ band and true insular activity are
only partially captured), and a continuous 10 s tasting window without a sharp
sensory trigger (ERP in Stage 06 is exploratory).
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--skip', nargs='*', default=[], help='stage numbers to skip')
    ap.add_argument('--only', nargs='*', default=[], help='run only these stages')
    args = ap.parse_args()

    log = setup_logging()
    cfg = load_config()
    status = {}
    for num, mod_name, title in STAGES:
        if num in args.skip or (args.only and num not in args.only):
            status[num] = 'skipped'
            continue
        log.info("#" * 64)
        log.info(f"# STAGE {num}: {title}")
        log.info("#" * 64)
        try:
            mod = importlib.import_module(mod_name)
            importlib.reload(mod)
            mod.main()
            status[num] = 'ok'
        except Exception as e:                          # noqa: BLE001
            status[num] = f'FAILED: {e}'
            log.error(f"Stage {num} failed: {e}\n{traceback.format_exc()}")

    # Assemble REPORT_FULL.md
    rdir = cfg['paths']['reports']
    parts = [INTRO]
    for num, _mod, title in STAGES:
        fpath = os.path.join(rdir, REPORT_FILES[num])
        if os.path.exists(fpath):
            with open(fpath, 'r', encoding='utf-8') as fh:
                parts.append(fh.read())
        else:
            parts.append(f"# Stage {num} — {title}\n\n*(not generated: {status.get(num)})*")
    parts.append(DISCUSSION)

    def _status_label(num):
        s = status.get(num)
        if s == 'skipped' and os.path.exists(os.path.join(rdir, REPORT_FILES[num])):
            return 'ok (cached from previous run)'
        return s
    parts.append("\n## Stage status\n\n" +
                 '\n'.join(f"- Stage {n}: {_status_label(n)}" for n, _m, _t in STAGES))

    out = report_path(cfg, 'REPORT_FULL.md')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write('\n\n'.join(parts) + '\n')
    log.info(f"\nFULL REPORT → {out}")
    log.info("Stage status: " + ', '.join(f'{n}={s}' for n, s in status.items()))


if __name__ == '__main__':
    main()
